Allow users by
pagarme/flottbot pull request #1
Opened 2019-04-10 12:52 UTC by xduh

### ❤ THANKS FOR HELPING OUT :D

## Proposed change

Enable user restriction by user_id

## Types of changes

What types of changes is this pull request introducing to flottbot? _Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

You can fill this out after creating your PR. _Put an `x` in the boxes that apply_

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

2019-04-10 15:42 UTC, jonatasnona requested changes

2019-04-10 15:42 UTC, jonatasnona commented on models/rule.go
> +	AllowUserIds       []string `mapstructure:"allow_userids" binding:"omitempty"`
acho que seria melhor usar `AllowUsersIds`.

2019-04-10 15:50 UTC, xduh commented on models/rule.go
> +	AllowUserIds       []string `mapstructure:"allow_userids" binding:"omitempty"`
Acho que faz mais sentido manter o mesmo padrão de `AllowUserGroups` \ `allow_usergroups`

2019-04-10 17:00 UTC, jonatasnona commented on models/rule.go
> +	AllowUserIds       []string `mapstructure:"allow_userids" binding:"omitempty"`
mas cho que nesse caso é pq um usuário pode estar em vários grupos, no caso dos ids acho que é diferente... são ids de usuários e não ids de um usuário. 🤔

2019-04-10 17:33 UTC, xduh commented on models/rule.go
> +	AllowUserIds       []string `mapstructure:"allow_userids" binding:"omitempty"`
Da doc do Flattbot: 
```
allow_usergroups (yaml array) An array of user groups that are permitted to execute this rule.
```
recebe (uma array de) grupos de usuário, sendo assim `allow_usergroups` receberia (uma array de ) ids de usuário

2019-04-11 14:02 UTC, jonatasnona approved these changes

2019-04-11 15:35 UTC, travoul approved these changes

2019-04-12 12:12 UTC, merged